// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/camelexample.proto

package com.mk.camel.proto;

public final class Camelexample {
  private Camelexample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TradeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required sint64 id = 1;
    boolean hasId();
    long getId();
    
    // optional double quantity = 2;
    boolean hasQuantity();
    double getQuantity();
    
    // optional double price = 3;
    boolean hasPrice();
    double getPrice();
    
    // optional int64 tradedate = 4;
    boolean hasTradedate();
    long getTradedate();
    
    // optional int64 settlementdate = 5;
    boolean hasSettlementdate();
    long getSettlementdate();
  }
  public static final class Trade extends
      com.google.protobuf.GeneratedMessage
      implements TradeOrBuilder {
    // Use Trade.newBuilder() to construct.
    private Trade(Builder builder) {
      super(builder);
    }
    private Trade(boolean noInit) {}
    
    private static final Trade defaultInstance;
    public static Trade getDefaultInstance() {
      return defaultInstance;
    }
    
    public Trade getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mk.camel.proto.Camelexample.internal_static_com_mk_camel_proto_Trade_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mk.camel.proto.Camelexample.internal_static_com_mk_camel_proto_Trade_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required sint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional double quantity = 2;
    public static final int QUANTITY_FIELD_NUMBER = 2;
    private double quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getQuantity() {
      return quantity_;
    }
    
    // optional double price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getPrice() {
      return price_;
    }
    
    // optional int64 tradedate = 4;
    public static final int TRADEDATE_FIELD_NUMBER = 4;
    private long tradedate_;
    public boolean hasTradedate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTradedate() {
      return tradedate_;
    }
    
    // optional int64 settlementdate = 5;
    public static final int SETTLEMENTDATE_FIELD_NUMBER = 5;
    private long settlementdate_;
    public boolean hasSettlementdate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getSettlementdate() {
      return settlementdate_;
    }
    
    private void initFields() {
      id_ = 0L;
      quantity_ = 0D;
      price_ = 0D;
      tradedate_ = 0L;
      settlementdate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, quantity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, tradedate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, settlementdate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, quantity_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, tradedate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, settlementdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mk.camel.proto.Camelexample.Trade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mk.camel.proto.Camelexample.Trade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mk.camel.proto.Camelexample.Trade prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mk.camel.proto.Camelexample.TradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mk.camel.proto.Camelexample.internal_static_com_mk_camel_proto_Trade_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mk.camel.proto.Camelexample.internal_static_com_mk_camel_proto_Trade_fieldAccessorTable;
      }
      
      // Construct using com.mk.camel.proto.Camelexample.Trade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        quantity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        tradedate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        settlementdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mk.camel.proto.Camelexample.Trade.getDescriptor();
      }
      
      public com.mk.camel.proto.Camelexample.Trade getDefaultInstanceForType() {
        return com.mk.camel.proto.Camelexample.Trade.getDefaultInstance();
      }
      
      public com.mk.camel.proto.Camelexample.Trade build() {
        com.mk.camel.proto.Camelexample.Trade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mk.camel.proto.Camelexample.Trade buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mk.camel.proto.Camelexample.Trade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mk.camel.proto.Camelexample.Trade buildPartial() {
        com.mk.camel.proto.Camelexample.Trade result = new com.mk.camel.proto.Camelexample.Trade(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.quantity_ = quantity_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tradedate_ = tradedate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.settlementdate_ = settlementdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mk.camel.proto.Camelexample.Trade) {
          return mergeFrom((com.mk.camel.proto.Camelexample.Trade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mk.camel.proto.Camelexample.Trade other) {
        if (other == com.mk.camel.proto.Camelexample.Trade.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasTradedate()) {
          setTradedate(other.getTradedate());
        }
        if (other.hasSettlementdate()) {
          setSettlementdate(other.getSettlementdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readSInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              quantity_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              price_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              tradedate_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              settlementdate_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required sint64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double quantity = 2;
      private double quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(double value) {
        bitField0_ |= 0x00000002;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double price = 3;
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int64 tradedate = 4;
      private long tradedate_ ;
      public boolean hasTradedate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTradedate() {
        return tradedate_;
      }
      public Builder setTradedate(long value) {
        bitField0_ |= 0x00000008;
        tradedate_ = value;
        onChanged();
        return this;
      }
      public Builder clearTradedate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tradedate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 settlementdate = 5;
      private long settlementdate_ ;
      public boolean hasSettlementdate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getSettlementdate() {
        return settlementdate_;
      }
      public Builder setSettlementdate(long value) {
        bitField0_ |= 0x00000010;
        settlementdate_ = value;
        onChanged();
        return this;
      }
      public Builder clearSettlementdate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        settlementdate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.mk.camel.proto.Trade)
    }
    
    static {
      defaultInstance = new Trade(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.mk.camel.proto.Trade)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mk_camel_proto_Trade_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mk_camel_proto_Trade_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/protobuf/camelexample.proto\022\022" +
      "com.mk.camel.proto\"_\n\005Trade\022\n\n\002id\030\001 \002(\022\022" +
      "\020\n\010quantity\030\002 \001(\001\022\r\n\005price\030\003 \001(\001\022\021\n\ttrad" +
      "edate\030\004 \001(\003\022\026\n\016settlementdate\030\005 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_mk_camel_proto_Trade_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_mk_camel_proto_Trade_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_mk_camel_proto_Trade_descriptor,
              new java.lang.String[] { "Id", "Quantity", "Price", "Tradedate", "Settlementdate", },
              com.mk.camel.proto.Camelexample.Trade.class,
              com.mk.camel.proto.Camelexample.Trade.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
